### PR TITLE
feat: add gh action for CI

### PR DESCRIPTION
**Pull request by macintoshpie**
## Changes
- move CI from travis to GH actions. Travis is no longer "free" for us so we are making the transition.

See that coveralls is still working here: https://coveralls.io/github/BuildingSync/selection-tool?branch=HEAD

### CODE REVIEW

**Comment by macintoshpie** [comment]
@nllong this action isn't being triggered, could you either increase my permissions in the repo or investigate yourself?
We might need to enable GH actions for the repo.

**Comment by nllong** [comment]
I've updated the branch protections to use the new GH actions (and removed travis). This looks good now, right?

**Comment by macintoshpie** [comment]
I goofed up squashing the commits, but I think we should be good once these tests pass

**Review by nllong — APPROVED** [review]
most excellent!

**Pull request merged**
