### PR TITLE
Increase font size and add white buildingsync logo

### LINKED ISSUE #93: Increase font size and use white buildingsync logo on headers

### PR DESCRIPTION
**Pull request by kflemin**
Fixes #93 
Screen Shot 2021-05-12 at 11 11 14 AM
Screen Shot 2021-05-12 at 11 11 28 AM

### CODE REVIEW

**Review by nllong — APPROVED** [review]
this is looking suweet!

**Comment by nllong** [comment]
I like the white BuildingSync logo too!
image

**Comment by aviveiros11** [comment]
@nllong /@kflemin can we merge this?

**Comment by nllong** [comment]
@aviveiros11 merged!

**Pull request merged**
